### ISSUE TITLE
RakNet_DLL_Debug_core_Win32.dll was not found.

### ISSUE THREAD

**Issue by Will737** [BenHandsley/ETS2MP-Remake#4]
I've never really used C++ before so I don't really know what I'm doing but every time I test the server core I get the following error. Does anyone know how I can fix this?
Any Help is much appreciated 
![image](https://user-images.githubusercontent.com/35170230/39095376-741ef7c2-4637-11e8-9311-e4de63de1cce.png)

**Comment by BenHandsley** [comment]
The file you're looking for should be in a library folder, once the project has been built.

From there, take the DLL and paste a version into your games location. I'm not a 100% sure this is correct, as I have not used this code in a long time.

**Comment by Will737** [comment]
Thanks for the help. I fixed it by just putting 'RakNet_DLL_Debug_core_Win32.dll' and 'RakNet_DLL_Retail_core_Win32.dll' in the same directory as the server.exe file, I found the two files in 'Vendor\SLikeNet\Lib\prebuild\VS_2017' so not 100% sure if their the right ones but it seems to work.
