### ISSUE TITLE
Client Core: Client.dll is not a valid Win32 application 

### ISSUE THREAD

**Issue by Will737** [BenHandsley/ETS2MP-Remake#6]
I get the following error every time I try to launch the Client Core. I'm guessing your meant to launch the core from the Client Launcher. Whereas I'm launching straight from the core. 
![image](https://user-images.githubusercontent.com/35170230/39096477-84cbbd1a-4648-11e8-9dee-8714662bbd33.png)

**Comment by BenHandsley** [comment]
From what I can tell, you're loading up the DLL file. When what should be happening is you should be launching the client program, and the program should do the rest for you.

Keep having a go at this, as I've not encountered this issue when I uploaded the code originally.
